<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26077" started-at="2018-11-22T12:12:42Z" finished-at="2018-11-22T12:13:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26077" started-at="2018-11-22T12:12:42Z" finished-at="2018-11-22T12:13:08Z">
      <class name="testcases.HappyFlowTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:testcases.HappyFlowTest@27d415d9]" name="setup" is-config="true" duration-ms="2670" started-at="2018-11-22T12:12:42Z" finished-at="2018-11-22T12:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="failedTest()[pri:1, instance:testcases.HappyFlowTest@27d415d9]" name="failedTest" duration-ms="3275" started-at="2018-11-22T12:12:45Z" finished-at="2018-11-22T12:12:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [personal-info] but found [career]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [personal-info] but found [career]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcases.HappyFlowTest.failedTest(HappyFlowTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failedTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testcases.HappyFlowTest@27d415d9]" name="teardown" is-config="true" duration-ms="3924" started-at="2018-11-22T12:12:49Z" finished-at="2018-11-22T12:12:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:testcases.HappyFlowTest@27d415d9]" name="setup" is-config="true" duration-ms="2011" started-at="2018-11-22T12:12:53Z" finished-at="2018-11-22T12:12:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="succesTest()[pri:1, instance:testcases.HappyFlowTest@27d415d9]" name="succesTest" duration-ms="10123" started-at="2018-11-22T12:12:55Z" finished-at="2018-11-22T12:13:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- succesTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testcases.HappyFlowTest@27d415d9]" name="teardown" is-config="true" duration-ms="3732" started-at="2018-11-22T12:13:05Z" finished-at="2018-11-22T12:13:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.HappyFlowTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
